services:
  www:
    build:
      dockerfile: ./dockerfile.www
    volumes:
      - "./fedimapper:/app/fedimapper"
      - "./db:/app/db"
      - "./docker/www/prestart.sh:/app/prestart.sh"
      - "./test.db:/app/test.db"
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: 'postgresql+psycopg2://dbuser:asdfghjkl123@db/main'
      DEBUG: true
      SQL_DEBUG: false
      RELOAD: true
    depends_on:
      - db

  ingest:
    build:
      dockerfile: ./dockerfile.ingest
    volumes:
      - "./fedimapper:/app/fedimapper"
      - "./db:/app/db"
      - "./docker/ingest/prestart.sh:/app/prestart.sh"
      - "./docker/ingest/start.sh:/app/start.sh"
      - "./test.db:/app/test.db"
    environment:
      DATABASE_URL: 'postgresql+psycopg2://dbuser:asdfghjkl123@db/main'
      DEBUG: true
      RELOAD: true
      NUM_PROCESSES: 2
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: asdfghjkl123
      POSTGRES_USER: dbuser
      POSTGRES_DB: main
    healthcheck:
      test: [ “CMD-SHELL”, “pg_isready” ]
      interval: 1s
      timeout: 5s
      retries: 10

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
