name: Black Formatting

on:
  push:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Python Version from File
        id: python_version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.python_version.outputs.PYTHON_VERSION }}

      - name: Install Dependencies
        run: make install

      - name: Test Formatting
        run: make black_check
