name: Import Sorting

on:
  push:

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Python Version from File
        id: python_version
        run: echo "python_version=$(cat .python-version)" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python_version }}

      - name: Install Dependencies
        run: make install

      - name: Test Formatting
        run: make isort_check
