name: PyTest

on:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Python Version from File
        id: python_version
        run: echo "::set-output name=version::$(cat VERSION)"

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ steps.python_version.outputs.version }}

      - name: Install Dependencies
        run: make install

      - name: Run Tests
        run: make pytest
